apiVersion: v1
kind: Service
metadata:
  name: springboottest-service
  namespace: backend
spec:
  type: LoadBalancer
  selector:
    app: springboottest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080